const random = {
  names: [
    "Steve Rogers",
    "Bucky",
    "Monica Everdawg",
    "Bond. James Bond.",
    "I'm the money",
    "Groot",
    "Broken Sword",
    "Gong Er",
    "Lisa",
    "Mark",
    "Gamora",
    "Prince Hapi",
    "John Connor",
    "Sarah Connor",
    "Ellen Ripley",
    "Hannibal Lector",
    "Red Dragon",
    "Heisenberg",
    "Willy Wonka",
    "Jack Burton",
    "Tango or Cash",
    "Samwise the Brave",
    "Gandalf",
    "Celeborn aka Da Bes",
    "Aragorn",
    "Galadriel",
    "Leeloo",
    "Mister Doctor",
    "Sherlock Holmes",
    "Parker with Parker shirt",
    "James 'Logan' Howlett",
    "Jeaaaan!",
    "Charles Xavier",
    "Rick Deckard",
    "Rachel",
    "KD6-3.7",
    "Jack Torrance",
    "Michael Myers",
    "Colonel Kurtz",
    "Roy Batty",
    "Dr. Ian Malcolm",
    "Agent Smith",
    "Mr. Anderson",
    "Morpheus",
    "J Money",
    "Danny Rand",
    "Ethan Hunt",
    "Dom Torreto",
    "The Rock",
    "Alice of Wonderland",
    "Elizabeth Swan",
    "Arwen",
    "Eowyn",
    "Furiosa",
    "Luna Lovegood",
    "Jade Fox",
    "Maria Hill",
    "Switch",
    "Rey...Skywalker?!",
    "Clarice Starling",
    "Talia al Ghul",
    "Mal",
    "Eleanor Rigby",
    "Joi",
    "Natasha Romanov",
    "Kylo Ren",
    "Leia Skywalker",
    "Lisbeth Salander",
    "Hermione Granger",
    "Harry Potter",
    "Ron Weasley",
    "Dolores Umbridge",
    "Nurse Ratched"
  ],
  placeholderMovies: [
    'The Room',
    'Samurai Cop',
    'Demolition Man',
    'The Wicker Man',
    'Blade 3',
    'Austin Powers',
    'Scary Movie',
    'Scary Movie 2',
    'Scary Movie 3',
    'Scary Movie 4',
    'Scary Movie 5',
    'Clown',
    'The Fast and the Furious',
    '2 Fast 2 Furious',
    'Fast 6',
    'Drug Wars',
    'Fast 7',
    'Alien: Resurrection',
    'Terminator: Genisys',
    'Three',
    'The Dinner',
    'Expendables 3',
    'Mimic 2',
    'Deep Star Six',
    'Batman vs Superman',
    'The Tag-Along',
    'The Secret of Moonacre',
    'The Trust',
    'Beyond the Gates',
    'Gantz: 0',
    'A Wrinkle in Time',
    'Catwoman',
    'Atlantic Rim',
    'Sharknado',
    'Mega Shark vs Giant Octopus',
    'Fant4stic Four',
    'Rage',
    'Bangkok Dangerous',
    'Drive Angry',
    'Sun Choke'
  ],
  quotes: [
    "Ya like dags?",
    "5 minutes Turkish!",
    "All those moments, lost in time",
    "Cells interlinked",
    "Kansas is going bye-bye",
    "I know kung-fu",
    "I am no man",
    "Mr. Filch, you don't understand",
    "Hogwarts, A History",
    "Hasta la vista, baby",
    "Open the pod bay doors, HAL",
    "Life, uh, finds a way",
    "Hello, Clarice",
    "I am Iron Man",
    "I can do this all day",
    "Kaneda, what do you see?!",
    "Is it safe?",
    "I can't explain it",
    "You wanna go home? Find Jason Bourne.",
    "What say you?!"
  ],
  streamingService: [
    { name: "Netflix",
      value: "netflix"
    },
    { name: "Amazon Prime",
      value: "prime"
    },
    { name: "Hulu",
      value: "hulu"
    },
    { name: "Vudu",
      value: "vudu"
    },
    { name: "HBO",
      value: "hbo"
    },
    { name: "VRV",
      value: "vrv"
    },
    { name: "Criterion Collection",
      value: "critcol"
    },
    { name: "Tubi",
      value: "tubi"
    },
    { name: "Viki",
      value: "viki"
    },
    {
      name: "Hoopla",
      value: "hoopla"
    },
    {
      name: "DVD/Bluray",
      value: "local"
    },
    { name: "Download",
      value: "dl"
    },
  ]
}

export default random;
